version: "3"

services:
  redis:
    image: redis
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: imnotusingclusteronthis
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - 15672:15672
      - 5672:5672

  mqtt:
    image: toke/mosquitto
    ports:
      - 1883:1883
      - 9001:9001


